version: '3.9'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./docker/volumes/dynamodb:/home/dynamodblocal/data
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8080:8001'
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
